### ISSUE TITLE
Cannot create PercolatorModel

### ISSUE THREAD

**Issue by kunruh9** [data-axle/elastic_record#64]
I've been trying to wrap my head around how ElasticRecord handles Percolate queries. When working directly with the Elasticsearch API, it makes sense. But in its current state, I don't see how ElasticRecord utilizes this.

The issue I'm seeing is that a [percolator query](https://www.elastic.co/guide/en/elasticsearch/reference/6.2/query-dsl-percolate-query.html#_sample_usage) requires documents in a given index to contain a `percolator` type field (i.e. `"query": { "type": "percolator" }`). Then, one can execute a percolator query with a given `document`.

However, I don't see how `PercolatorModel` can do this **unless** the model it is percolating has already been index with the `query` value explicitly defined, like so:
```ruby
Document.create({
    content: 'String of words',
    user: 'johndoe',
    query: { content: 'words' }
})
```
Only then can I see something like this working:
```ruby
DocumentQuery.percolate({
    content: 'String of words'
})
```

The README indicates that "Queries are registered and unregistered as query models are created and destroyed". However, `PercolatorModel` does not respond to any methods like `create`.

To me, it seems like there needs to be some code added to get Percolation working correctly for this library. I was planning on making these fixes since I'm working in the library right now, but wanted to make sure I'm not missing something here with its intended usage before I started down that path. Am I using the `PercolatorModel` incorrectly?

**Comment by kunruh9** [comment]
@matthuhiggins @dcromer

**Comment by dcromer** [comment]
You need to create the mapping ahead of time.  There are some rake tasks that will help you do this.

`rake index:create`
`rake index:reset #you already have the indexes`
`rake index:build #reindex everything`

> unless the model it is percolating has already been index with the query value explicitly defined, like so

The reason you can index a document before setting the mapping, and ES will guess the type, is called _dynamic mapping_
https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html

**Comment by kunruh9** [comment]
Hm, maybe I'm expecting more automation with the `PercolatorModel` than there actually is. Are there any places in content_system or axle_places that use percolation that I can reference?
